version: '3.8'

services:
  app:
    #image: aswanthkrshna/qpiai-pro-flyte-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "python", "main.py"]
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    network_mode: host
    volumes:
      - .:/app
