apiVersion: v1
kind: ConfigMap
metadata:
  name: qpiai-pro-azure-flyte-config
data:
  config.yaml: |
    admin:
      endpoint: dns:///flyte.qpiai-pro.tech:443
      authType: Pkce
      insecure: false
    console:
      endpoint: https://flyte.qpiai-pro.tech/console
    logger:
      show-source: true
      level: 6
    storage:
      type: custom
      bucketName: flyte
      custom:
        container: "flyteblobcontainer"
        enable-multicontainer: true
        connection: {}
        type: stow
        stow:
          kind: azure
          config:
            account: ${AZURE_STORAGE_ACCOUNT}
            key: ${AZURE_STORAGE_KEY}
      enableMultiContainer: true
